# Generated by Django 2.0 on 2020-08-31 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_mysqlports'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMysqlports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port', models.IntegerField()),
                ('user', models.CharField(default=None, max_length=15)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成日期')),
            ],
        ),
        migrations.CreateModel(
            name='CSpringports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port', models.IntegerField()),
                ('user', models.CharField(default=None, max_length=15)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成日期')),
            ],
        ),
    ]
